# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.
---
# (re))create the specified database.
# dbName - name of the database to (re)create
# forceRecreation - if true, the databases will be deleted (if it exists) and recreated. If false, it will not be recreated.

- name: check if {{ dbName }} with {{ db_provider }} exists
  uri:
    url: "{{ db_protocol }}://{{ db_host }}:{{ db_port }}/{{ dbName }}"
    method: HEAD
    status_code: 200,404
    user: "{{ db_username }}"
    password: "{{ db_password }}"
    force_basic_auth: yes
  register: response
  when: db.backend == "CouchDB"

- name: delete the {{ dbName }} with {{ db_provider }}
  uri:
    url: "{{ db_protocol }}://{{ db_host }}:{{ db_port }}/{{ dbName }}"
    method: DELETE
    status_code: 200,404
    user: "{{ db_username }}"
    password: "{{ db_password }}"
    force_basic_auth: yes
  when: db.backend == "CouchDB" and forceRecreation == True and response.status == 200

- name: create {{ dbName }} with {{ db_provider }}
  uri:
    url: "{{ db_protocol }}://{{ db_host }}:{{ db_port }}/{{ dbName }}"
    method: PUT
    status_code: 200,201
    user: "{{ db_username }}"
    password: "{{ db_password }}"
    force_basic_auth: yes
  when: db.backend == "CouchDB" and (forceRecreation == True or response.status == 404)

- name: recreate {{ dbName }} in MongoDB
  vars:
    commands: |
      db=db.getSiblingDB('{{ mongodb_database }}');
      db.auth('{{ db_username }}', '{{ db_password }}');
      db.getCollection('{{ dbName }}').drop();
      db.createCollection('{{ dbName }}');
  shell: docker exec mongodb mongo {{ mongodb_connect_string }} --eval "{{ commands }}"
  when: db.backend == "MongoDB" and forceRecreation == True
