# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.
---
# WARNING: This playbook wipes the database. This action is not reversible. Be very careful and know what you are doing.

- hosts: ansible
  tasks:
  - name: create necessary indexes on {{ db.whisk.actions }}
    mongodb:
      database: "{{ db.mongodb.database }}"
      login_user: "{{ db.credentials.admin.user }}"
      login_password: "{{ db.credentials.admin.pass }}"
      login_host: "{{ db.host }}"
      login_port: "{{ db.port }}"
      login_database: "{{ db.mongodb.database }}"
      collection: "{{ db.whisk.actions }}"
      indexes:
        - index:
            - field: "namespace"
              direction: -1
            - field: "updated"
              direction: -1
        - index:
            - field: "_computed.rootns"
              direction: -1
            - field: "updated"
              direction: -1
      mode: "index"

  - name: create necessary indexes on {{ db.whisk.activations }}
    mongodb:
      database: "{{ db.mongodb.database }}"
      login_user: "{{ db.credentials.admin.user }}"
      login_password: "{{ db.credentials.admin.pass }}"
      login_host: "{{ db.host }}"
      login_port: "{{ db.port }}"
      login_database: "{{ db.mongodb.database }}"
      collection: "{{ db.whisk.activations }}"
      indexes:
        - index:
            - field: "namespace"
              direction: -1
            - field: "start"
              direction: -1
        - index:
            - field: "_computed.nspath"
              direction: -1
            - field: "start"
              direction: -1
        - index:
            - field: "start"
              direction: -1
      mode: "index"
